// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBMZ7dvyZdP4tq5hHGAKWUYWtfGdBuG2Qg",
    authDomain: "commurur.firebaseapp.com",
    projectId: "commurur",
    storageBucket: "commurur.firebasestorage.app",
    messagingSenderId: "224534924824",
    appId: "1:224534924824:web:2536106c25b36bbf377d6d"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8mQIE7OfpMUc4yUK9AnqTcBk7R9AxjCs',
    appId: '1:224534924824:android:d25e2b0bb7e45edb377d6d',
    messagingSenderId: '224534924824',
    projectId: 'commurur',
    storageBucket: 'commurur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABf3AL9vfr9UgxyOHGjQULqvZlB55Z8lE',
    appId: '1:224534924824:ios:68ae53bfba8fdf36377d6d',
    messagingSenderId: '224534924824',
    projectId: 'commurur',
    storageBucket: 'commurur.firebasestorage.app',
    iosBundleId: 'com.example.commurur',
  );
} 